#
# Created by Xiaolei Li on 8/1/23, 9:09 PM
# Copyright (c) 2023 Xiaolei Li.
# All rights reserved.
# Last modified 8/1/23, 9:09 PM
#

quarkus.log.console.format=%d{yyyy-MM-dd HH:mm:ss}.%r [%p] [%C.%M(%L)] (%t) %m%n

quarkus.rest-client."com.lxlgarnett.githubprofilestatus.client.GitHubUserService".url=https://api.github.com
quarkus.rest-client."com.lxlgarnett.githubprofilestatus.client.GitHubUserService".scope=javax.inject.Singleton

quarkus.rest-client."com.lxlgarnett.githubprofilestatus.client.GitHubRepositoryService".url=https://api.github.com
quarkus.rest-client."com.lxlgarnett.githubprofilestatus.client.GitHubRepositoryService".scope=javax.inject.Singleton
